### ISSUE TITLE
Usar 100% da viewport

### ISSUE THREAD

**Issue by ianfilipe** [raulcraveiro/youtube-without-distractions#1]
Que tal em vez de apenas esconder, utilizar 100% da tela, algo como acontece +/- nos smartphones, em que tudo vira uma grande coluna?

Se 100% não ficar confortável, poderia utilizar o máximo possível mantendo a proporção do vídeo. Dei uma olhada no inspetor e eles utilizam um calc() para definir isso.

Acho que seria legal 😁

**Comment by ianfilipe** [comment]
Percebi que playlists fazem uso da sidebar, então, deixa para lá ahaha

Usar o modo teatro já diminui um pouco do desconforto.

Se pensar em algo melhor, comento por aqui.

**Comment by raulcraveiro** [comment]
@ianfilipe Ads ainda aparecem na sidebar, as playlists também e eu aaaacho que o chat de live também é dentro da sidebar :thinking:

**Comment by ianfilipe** [comment]
Simmm, me precipitei pela agonia de ver um grande espaço vazio à direita ahahaha
